### ISSUE TITLE
About Compability

### ISSUE THREAD

**Issue by danidoco** [fd-guiner/uku#2]
### HTML Compabilty
Uku can be only run on **HTML5**

### Browser Support
-  Internet Explorer ❌ 
-  Edge ✔️
- Chrome ✔️
- Chromium ✔️ 
-  Firefox ✔️ 
- Safari ✔️
- Opera ✔️ 
- Whale ✔️ 
- Vivaldi ✔️
- Brave ✔️
- Tor ✔️
- Maxthon (after Maxthon 3) ✔️ 
- Waterfox ✔️
- SeaMonkey ✔️  
- Torch ✔️ 
- Pale Moon ✔️ 
- Epic ✔️ 
- SRWare Iron ✔️ 
- Opera GX ✔️

**Comment by oldp00** [comment]
why not support IE? because of HTML5?

**Comment by danidoco** [comment]
IE supports HTML5
However, IE has become heavy due to plug-ins and it is far from the web standard.
IE has slowed and insecure.
**Also i hate IE**

~~sorry microsoft~~

**Comment by oldp00** [comment]
Not officially support, but I think IE will work~ because IE supports HTML5

**Comment by danidoco** [comment]
surrender

**Comment by danidoco** [comment]
I'll surrender.
